apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: hf-itcne24-semarbeit5-developperhub-inno
  title: MSVC Lizenztool
  description: Devloper Hub für die Semesterarbeit 5 - Inno

  tags:
    - developer-hub
    - backstage
    - k8s
    - kustomize

  annotations:
    github.com/project-slug: Radball-Migi/HF-ITCNE24-SemArbeit5-DevelopperHub-Inno
    backstage.io/source-location: url:https://github.com/Radball-Migi/HF-ITCNE24-SemArbeit5-DevelopperHub-Inno
    backstage.io/techdocs-ref: url:https://github.com/Radball-Migi/HF-ITCNE24-SemArbeit5-DevelopperHub-Inno/tree/main
    backstage.io/kubernetes-id: hf-itcne24-semarbeit5-developperhub-inno

  links:
    - url: https://github.com/Radball-Migi/HF-ITCNE24-SemArbeit5-DevelopperHub-Inno
      title: GitHub Repository
      icon: github

    - url: https://radball-migi.github.io/HF-ITCNE24-SemArbeit5-DevelopperHub-Inno/
      title: Projektdokumentation
      icon: docs

spec:
  type: service
  lifecycle: experimental
  owner: group:default/hf-itcne24
  system: semesterarbeiten

